//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr7
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTowarys
    {
        public int order_id { get; set; }
        public int towar_id { get; set; }
        public int price_fact { get; set; }
        public int id { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Towary Towary { get; set; }
    }
}
