//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartPending
    {
        public int id { get; set; }
        public int id_part { get; set; }
        public int time_remains { get; set; }
        public int count { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
